#!/bin/sh

/usr/bin/invoke_app "$@" -t spiroflask1 \
    -u wrwroxy-0.1 \
    -w "none" \
    -e "FLASK_APP=@tool/www/run.py" \
    -c "xview -fullscreen -onroot @tool/doc/flask.png" \
    -c "wrwroxy --stream-log --logfile /dev/null" \
    -C "@tool/bin/run_flask.sh --host 0.0.0.0 --port 8001"
