#!/bin/sh

/usr/bin/invoke_app "$@" -t spiroflask1 \
    -u wrwroxy-0.1 \
    -u anaconda-4.1 \
    -w "none" \
    -e "FLASK_APP=@tool/www/run.py"
    -c "xview -fullscreen -onroot \${JUPYTER_LOGO_PATH}" \
    -c "wrwroxy --stream-log --logfile /dev/null" \
    -C "flask run --host 0.0.0.0 --port 8001"
